name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  gather-snippets:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Building
        run: npm run build

      - name: Committing
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: gathered
          branch: ${{ github.head_ref }}
