name: Gather Snippets

on:
  push:
    branches:
      - main

jobs:
  gather-snippets:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Gather
        run: node ./gather-snippets.js
