name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 'v16.10.0'

      - name: Installing
        run: npm install

      - name: Gathering
        run: npm run gather

      - name: Bundling
        run: npm run bundle

      - name: Committing
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: published
          branch: ${{ github.head_ref }}

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: publish # Wait for publish job to complete
    if: always() && needs.publish.result == 'success' # Run even if other jobs fail, but only if publish succeeded
    continue-on-error: true # Don't fail the whole workflow if deploy fails
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
