name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  gather-snippets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Publishing
        run: npm publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: published
          branch: ${{ github.head_ref }}
